apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: "aristotleplatform-6596"
    labels:
        app: "aristotleplatform-6596"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: aristotle-education-platform-prod-aristotleplatform-6596.b34420f073ab48d8a1fe.canadacentral.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: "aristotleplatform-6596"
                servicePort: 80