apiVersion: v1
kind: Service
metadata:
  name: aristotle-app
  namespace: aristotle-app-staging

spec:
  ports:
    - protocol: TCP
      name: web
      port: 8080
  selector:
    app: aristotle-app