name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Registry
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/luscinia-enterprises/aristotle-app:latest
    - name: Push the Docker image
      run: docker push ghcr.io/luscinia-enterprises/aristotle-app:latest
